### ISSUE TITLE
zookeeper template not working for other than 3 nodes in the zookeeper ensemble

### ISSUE THREAD

**Issue by FrankSiegemund** [Azure/azure-quickstart-templates#1898]
zookeeper-cluster-ubuntu-vm: https://azure.microsoft.com/en-us/documentation/templates/zookeeper-cluster-ubuntu-vm/

### Issue Details

Template gives the option to deploy zookeeper ensemble with variable number of nodes. However, the template really only works for 3 nodes. This is because the zookeeper.sh script does only add the first 3 nodes to the ensamble. This needs to be changed.

### Repro steps (*if necessary, delete otherwise*)
1. Deploy with 5 nodes and look at logs for the 4th or 5th node. Here is an example error message from the log files:

2016-05-02 06:37:43,246 [myid:5] - ERROR [main:QuorumPeerMain@89] - Unexpected exception, exiting abnormally
java.lang.RuntimeException: My id 5 not in the peer list
        at org.apache.zookeeper.server.quorum.QuorumPeer.startLeaderElection(QuorumPeer.java:583)
        at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:502)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:153)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:111)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)

**Comment by singhkay** [comment]
Thanks @FrankSiegemund I'll put this down as a task/enhancement

@ggalow - If you're still working on enhancing this, can you look at this as well?

**Comment by ggalow** [comment]
Yeah I wanted to fix this as well. Picking this up this week.

**Comment by singhkay** [comment]
Awesome! Thanks @ggalow

**Comment by FrankSiegemund** [comment]
I created this pull request #1907 

Can you please take a look?

If you consider doing more work on this example template, can you improve security by using network security groups? Right now, the VNET is very open.
