### ISSUE TITLE
Unable to install elastic search using template

### ISSUE THREAD

**Issue by sheebaangel** [Azure/azure-quickstart-templates#2269]
azure-quickstart-templates/elasticsearch/ ( https://github.com/Azure/azure-quickstart-templates/tree/master/elasticsearch )

unable to install elastic search extensions in created VMs

Error Details:
New-AzureRmResourceGroupDeployment : 12:56:31 PM - Resource Microsoft.Compute/virtualMachines/extensions
'esclustertest-master-vm0/installelasticsearch' failed with message 'The resource operation completed with terminal
provisioning state 'Failed'.'
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -Name esarmDeployment -ResourceGro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

**New-AzureRmResourceGroupDeployment : 12:56:31 PM - VM has reported a failure when processing extension
'installelasticsearch'. Error message: "Enable failed: Failed with error: HTTP Error 404: The specified resource does
not exist.,** Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/customscript.py", line 83, in main
    daemon(hutil)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/customscript.py", line 284, in daemon
    retry_count = download_files_with_retry(hutil, retry_count, wait)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/customscript.py", line 123, in
download_files_with_retry
    download_files(hutil)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/customscript.py", line 229, in
download_files
    download_external_files(blob_uris, cmd, hutil)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/customscript.py", line 430, in
download_external_files
    download_external_file(uri, command, hutil)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/customscript.py", line 440, in
download_external_file
    download_and_save_file(uri, file_path)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/customscript.py", line 451, in
download_and_save_file
    src = urllib2.urlopen(uri, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: The specified resource does not exist.
".

**Comment by russcam** [comment]
@sheebaangel take a look at [Elastic's ARM template](https://github.com/elastic/azure-marketplace), which is frequently updated
