### ISSUE TITLE
301-storage-spaces-direct - Error Keyset does not exist - HResult -2146233087 

### ISSUE THREAD

**Issue by petetakacs** [Azure/azure-quickstart-templates#2912]
[301-storage-spaces-direct](https://github.com/Azure/azure-quickstart-templates/tree/master/301-storage-spaces-direct)

### Issue Details
When deploying this template I receive an error at s2dconfig. 

With in Windows these are the errors:
Job {227229A7-C82F-11E6-A943-000D3A2753B6} : 
Message Error occured: 'An error occurred while performing the operation.', failed after '10' times 
HResult -2146233087 
StackTrack    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32& resultStatusHandle, Collection`1& result, ErrorRecord& errorRecord, PSModuleInfo localRunSpaceModuleInfo)

Job {227229A7-C82F-11E6-A943-000D3A2753B6} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [xCluster]FailoverCluster and Source Info is C:\Packages\Plugins\Microsoft.Powershell.DSC\2.21.0.0\DSCWork\config-s2d.ps1.0\ConfigS2D.ps1::114::9::xCluster. Error Message is PowerShell DSC resource MicrosoftAzure_xCluster  failed to execute Set-TargetResource functionality with error message: Error occured: 'An error occurred while performing the operation.', failed after '10' times .

Job {227229A7-C82F-11E6-A943-000D3A2753B6} : 
MIResult: 1
Error Message: PowerShell DSC resource MicrosoftAzure_xCluster  failed to execute Set-TargetResource functionality with error message: Error occured: 'An error occurred while performing the operation.', failed after '10' times 
Message ID: ProviderOperationExecutionFailure
Error Category: 7
Error Code: 1
Error Type: MI

When I run the failover cluster add node wizard. the second node cannot be added because of error: Keyset does not exist

I have found this article: http://chrishayward.co.uk/2015/07/02/windows-server-2012-r2-add-cluster-node-cluster-service-keyset-does-not-exist/
But I don't know if this is really the fix? Does anyone have this keyset problem?

I am using windows server 2016

**Comment by petetakacs** [comment]
I have tested the workaround as proposed http://chrishayward.co.uk/2015/07/02/windows-server-2012-r2-add-cluster-node-cluster-service-keyset-does-not-exist/, and it works. But now i'm getting an error at creating share script:
Job {32DA7313-C83E-11E6-A943-000D3A2753B6} : 
This event indicates that a non-terminating error was thrown when DSCEngine was executing Set-TargetResource on MSFT_ScriptResource DSC resource. FullyQualifiedErrorId is Windows System Error 1332,New-SmbShare. Error Message is No mapping between account names and security IDs was done. .

**Comment by petetakacs** [comment]
The SOFS computer object cannot be created because the cluster computer object needs delegation on the OU where the SOFS computer object will be placed. After I delegated this permission(create computer object) to the cluster computer object, the SOFS is created and I it all works. I retriggered the DSC-config within the VM manually.
