### ISSUE TITLE
OpenShift Origin - template provisioning failure

### ISSUE THREAD

**Issue by cimorar** [Azure/azure-quickstart-templates#2988]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Azure/azure-quickstart-templates 

### Issue Details
Hello,
I experience OpenShift template provisioning failure both via Portal and Azure CLI. In both ways, I got the same error, which is something like :
===========
    "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'deployOpenShift'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\"."
===========

Log snippet:
==========
info:    Resource 'rtuuxttbyllumnsa' of type 'Microsoft.Storage/storageAccounts' provisioning status is Succeeded
info:    Resource 'zuvh3pr2wxjtkmsa' of type 'Microsoft.Storage/storageAccounts' provisioning status is Succeeded
info:    Resource 'nodes' of type 'Microsoft.Compute/availabilitySets' provisioning status is Succeeded
error:   Deployment provisioning state was not successful
error:   The resource operation completed with terminal provisioning state 'Failed'.
error:   At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
error:   {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'deployOpenShift'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\"."
      }
    ]
  }
}
error:   The resource operation completed with terminal provisioning state 'Failed'.
error:   VM has reported a failure when processing extension 'deployOpenShift'. Error message: "Enable failed: failed to execute command: command terminated with exit status=2".
data:    DeploymentName     : os
data:    ResourceGroupName  : 2017012305osrg
data:    ProvisioningState  : Failed
data:    Timestamp          : 2017-01-23T11:40:38.160Z
data:    Mode               : Incremental
data:    CorrelationId      : c86d2f22-2f35-45fb-a841-0a2da4c44569
data:    DeploymentParameters :
data:    Name                                   Type          Value                                                        
data:    -------------------------------------  ------------  ------------------------------------------------------------------------------------------------
data:    _artifactsLocation                     String        https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/openshift-origin-rhel/
data:    masterVmSize                           String        Standard_DS2_v2                                              
data:    nodeVmSize                             String        Standard_DS2_v2                                              
data:    osImage                                String        centos                                                       
data:    openshiftMasterHostname                String        master                                                       
data:    openshiftMasterPublicIpDnsLabelPrefix  String        os-master-rci2017012201rci                                   
data:    nodeLbPublicIpDnsLabelPrefix           String        os-node-rci2017012201rci                                     
data:    nodePrefix                             String        node                                                         
data:    nodeInstanceCount                      Int           2                                                            
data:    adminUsername                          String        radim                                                        
data:    adminPassword                          SecureString  undefined                                                    
data:    sshPublicKey                           SecureString  undefined                                                    
data:    subscriptionId                         String        xxxxx                         
data:    keyVaultResourceGroup                  String        2017012301keyvaultrg                                         
data:    keyVaultName                           String        os2017012301kv                                               
data:    keyVaultSecret                         SecureString  undefined                                                    
data:    defaultSubDomainType                   String        xipio                                                        
data:    defaultSubDomain                       String        xipio                                                        
info:    group deployment create command OK

[os_armtemplate_failure.txt](https://github.com/Azure/azure-quickstart-templates/files/723527/os_armtemplate_failure.txt)

**Comment by 486** [comment]
Hi, I have the same problem. It looks like it is an issue with an ansible task (run during deployOpenShift.sh) that cannot be run over SSH, failing with **Failed to connect to the host via ssh: ControlPath too long**:

```
Generating keys
Configuring SSH ControlPath to use shorter path name
Generating Ansible hosts file
Cloning into '/home/openshift-admin/openshift-ansible'...
Executing Ansible playbook

PLAY [Create initial host groups for localhost] ********************************

TASK [include_vars] ************************************************************
ok: [localhost]

TASK [Evaluate group l_oo_all_hosts] *******************************************
ok: [localhost] => (item=openshift-master.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)
ok: [localhost] => (item=-0.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)
ok: [localhost] => (item=-1.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)

PLAY [Create initial host groups for all hosts] ********************************

TASK [include_vars] ************************************************************
ok: [openshift-master.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net]
ok: [-0.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net]
ok: [-1.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net]

PLAY [Populate config host groups] *********************************************

TASK [fail] ********************************************************************
skipping: [localhost]

TASK [fail] ********************************************************************
skipping: [localhost]

TASK [fail] ********************************************************************
skipping: [localhost]

TASK [fail] ********************************************************************
skipping: [localhost]

TASK [fail] ********************************************************************
skipping: [localhost]

TASK [fail] ********************************************************************
skipping: [localhost]

TASK [Evaluate oo_all_hosts] ***************************************************
ok: [localhost] => (item=openshift-master.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)
ok: [localhost] => (item=-0.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)
ok: [localhost] => (item=-1.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)

TASK [Evaluate oo_masters] *****************************************************
ok: [localhost] => (item=openshift-master.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)

TASK [Evaluate oo_etcd_to_config] **********************************************

TASK [Evaluate oo_masters_to_config] *******************************************
ok: [localhost] => (item=openshift-master.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)

TASK [Evaluate oo_nodes_to_config] *********************************************
ok: [localhost] => (item=openshift-master.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)
ok: [localhost] => (item=-0.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)
ok: [localhost] => (item=-1.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)

TASK [Add master to oo_nodes_to_config] ****************************************
skipping: [localhost] => (item=openshift-master.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net)

TASK [Evaluate oo_first_etcd] **************************************************
skipping: [localhost]

TASK [Evaluate oo_first_master] ************************************************
ok: [localhost]

TASK [Evaluate oo_lb_to_config] ************************************************

TASK [Evaluate oo_nfs_to_config] ***********************************************

PLAY [Ensure that all non-node hosts are accessible] ***************************

TASK [setup] *******************************************************************
fatal: [openshift-master.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net]: UNREACHABLE! => {"changed": false, "msg": "F
ailed to connect to the host via ssh: ControlPath too long\r\n", "unreachable": true}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/home/openshift-admin/openshift-ansible/playbooks/byo/config.retry
PLAY RECAP *********************************************************************
-0.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net : ok=1    changed=0    unreachable=0    failed=0
-1.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net : ok=1    changed=0    unreachable=0    failed=0
localhost                  : ok=7    changed=0    unreachable=0    failed=0
openshift-master.dhg1gelm1t5urj4dr2cbdl3oab.ax.internal.cloudapp.net : ok=1    changed=0    unreachable=1    failed=0
```

**Comment by 486** [comment]
So I was able to fix this by using the latest ansible and not setting `control_path` in ansible.cfg (latest ansible uses short hashes as control path by default).

After that ansible complained that the OpenShift version was 1.3.3 and not 1.4 as defined:
```
Detected OpenShift version 1.3.3 does not match requested openshift_release 1.4. You may need to adjust your yum
repositories, inventory, or run the appropriate OpenShift upgrade playbook.
```
 So I downgraded to these values:
```
openshift_release=v1.3
openshift_image_tag=v1.3.0
```

You can see what I did here:
https://github.com/486/azure-quickstart-templates/blob/master/openshift-origin-rhel/scripts/deployOpenShift.sh#L28-L53
https://github.com/486/azure-quickstart-templates/blob/master/openshift-origin-rhel/scripts/masterPrep.sh#L27

That helped to move further along, but now I am stuck with:
```
TASK [Evaluate oo_containerized_master_nodes] **********************************
skipping: [localhost] => (item=openshift-master.something_redacted.ax.internal.cloudapp.net)
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'hostvars[item].openshift.common is defined a
nd hostvars[item].openshift.common.is_containerized | bool and (item in groups.oo_nodes_to_config and item in groups.oo_mas
ters_to_config)' failed. The error was: error while evaluating conditional (hostvars[item].openshift.common is defined and
hostvars[item].openshift.common.is_containerized | bool and (item in groups.oo_nodes_to_config and item in groups.oo_master
s_to_config)): 'dict object' has no attribute 'openshift'\n\nThe error appears to have been in '/home/openshift-admin/opens
hift-ansible/playbooks/common/openshift-node/config.yml': line 39, column 5, but may\nbe elsewhere in the file depending on
 the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: Evaluate oo_containerized_master_nod
es\n    ^ here\n"}
```

Any help would be highly appreciated!

**Comment by pascals-msft** [comment]
Hi,
I had the same first error, which I resolved by replacing $NODE by $NODEPREFIX in scripts/deployOpenShift.sh:
https://github.com/pascals-msft/azure-quickstart-templates/commit/0a0915ef71eceec17ddfead6e5865d1d8a8c3009

But I run into another error in the Ansible master playbook:

```
TASK [openshift_master : set_fact] *********************************************
task path: /home/azureuser/openshift-ansible/roles/openshift_master/tasks/main.yml:150
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 443, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 248, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 373, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 427, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 383, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 583, in do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/home/azureuser/openshift-ansible/filter_plugins/openshift_master.py", line 492, in translate_idps
    Dumper=AnsibleDumper)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 215, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 101, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: htpasswd_auth

fatal: [master.qbrre2b2lzbe3gka03du3nmp0g.ax.internal.cloudapp.net]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/home/azureuser/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0   
master.qbrre2b2lzbe3gka03du3nmp0g.ax.internal.cloudapp.net : ok=161  changed=3    unreachable=0    failed=1   
node-0.qbrre2b2lzbe3gka03du3nmp0g.ax.internal.cloudapp.net : ok=49   changed=0    unreachable=0    failed=0   
node-1.qbrre2b2lzbe3gka03du3nmp0g.ax.internal.cloudapp.net : ok=49   changed=0    unreachable=0    failed=0   
```


Thanks!
