### ISSUE TITLE
201-vm-winrm-windows - Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (404) Not Found.".

### ISSUE THREAD

**Issue by joe-burrows** [Azure/azure-quickstart-templates#3942]
https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-winrm-windows

### Issue Details

Error when using in ARM template
Artifact fails with the below error every time:

The resource operation completed with terminal provisioning state 'Failed'. VM has reported a failure when processing extension 'customScriptArtifact-183362431'. Error message: "Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (404) Not Found.".

### Repro steps (*if necessary, delete otherwise*)
1. http://www.visualstudiogeeks.com/blog/DevOps/Configure-winrm-with-ARM-template-in-AzureDevTestLab-VM-deployment-using-PowerShell-artifact
2.
3.
4.
5.

**Comment by joe-burrows** [comment]
Actually I see the latest commit deleted winrmconf.cmd, will update our ARM templates

**Comment by sadeyemo** [comment]
Hello,

I am facing the same issue, however, in my case the initiator is a VSTS "**Azure File Copy**" task with the "**Enable Copy Prerequisites**" feature enabled. The task recently started to fail with: 

...
2017-09-28T08:33:08.8436751Z ##[warning]'##vso[task.logissue type=error;code={"Task_Internal_Error":Failed to enable copy prerequisites. Long running operation failed with status 'Failed'.' contains logging command keyword '##vso', but it's not a legal command. Please reference documentation to fix any potentially syntax error (http://go.microsoft.com/fwlink/?LinkId=817296)
2017-09-28T08:33:08.8436751Z ##vso[task.logissue type=error;code={"Task_Internal_Error":Failed to enable copy prerequisites. Long running operation failed with status 'Failed'.
2017-09-28T08:33:08.8436751Z ErrorCode: VMExtensionProvisioningError
2017-09-28T08:33:08.8436751Z ErrorMessage: **VM has reported a failure when processing extension 'WinRMCustomScriptExtension'. Error message: "Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (404) Not Found.".**
2017-09-28T08:33:08.8436751Z StartTime: 9/28/2017 9:22:06 AM
2017-09-28T08:33:08.8436751Z EndTime: 9/28/2017 9:32:41 AM
2017-09-28T08:33:08.8436751Z OperationID: 011a2015-8c0b-4de2-993d-4bfaa8f7a89d
2017-09-28T08:33:08.8436751Z Status: Failed};]
2017-09-28T08:33:09.2413000Z ##[error]Failed to enable copy prerequisites. Long running operation failed with status 'Failed'.
ErrorCode: VMExtensionProvisioningError
ErrorMessage: VM has reported a failure when processing extension 'WinRMCustomScriptExtension'. Error message: "Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (404) Not Found.".
StartTime: 9/28/2017 9:22:06 AM
EndTime: 9/28/2017 9:32:41 AM
OperationID: 011a2015-8c0b-4de2-993d-4bfaa8f7a89d
Status: Failed
...

Investigating further, I find the following in the **custom script handler** logs:

...
[6464+00000001] [09/28/2017 08:22:31.56] [INFO] Downloading files specified in configuration...
[6464+00000001] [09/28/2017 08:22:31.63] [INFO] DownloadFiles: File not in Azure storage, fileUri = https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/ConfigureWinRM.ps1
[6464+00000001] [09/28/2017 08:22:31.63] [INFO] DownloadFileAsync: Downloading file to fileDownloadLocation = Downloads\0\ConfigureWinRM.ps1
[6464+00000001] [09/28/2017 08:22:31.73] [INFO] DownloadFiles: File not in Azure storage, fileUri = https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/makecert.exe
[6464+00000001] [09/28/2017 08:22:31.73] [INFO] DownloadFileAsync: Downloading file to fileDownloadLocation = Downloads\0\makecert.exe
[6464+00000001] [09/28/2017 08:22:31.78] [INFO] DownloadFiles: File not in Azure storage, fileUri = https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/winrmconf.cmd
[6464+00000001] [09/28/2017 08:22:31.79] [INFO] DownloadFileAsync: Downloading file to fileDownloadLocation = Downloads\0\winrmconf.cmd
[6464+00000001] [09/28/2017 08:22:31.81] [WARN] DownloadFileAsync: **Error in downloading file from https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/winrmconf.cmd, retry count 0**, exception: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Program.DownloadFileWithRetries(String fileUri, String downloadDir, Int32 maxRetryCount, Int32 retryIntervalInSeconds).
...
[6464+00000001] [09/28/2017 08:32:17.98] [WARN] DownloadFileAsync: **Error in downloading file from https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/winrmconf.cmd, retry count 39**, exception: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Program.DownloadFileWithRetries(String fileUri, String downloadDir, Int32 maxRetryCount, Int32 retryIntervalInSeconds).
[6464+00000001] [09/28/2017 08:32:33.01] [ERROR] DownloadFiles: Encountered an error while downloading files. Cancelling download tasks. Exception: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Program.DownloadFileWithRetries(String fileUri, String downloadDir, Int32 maxRetryCount, Int32 retryIntervalInSeconds)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Program.DownloadFiles(IList`1 fileUriStrs, ProtectedSettings storageAccountSettings, String downloadDir)
[6464+00000001] [09/28/2017 08:32:33.01] [FATAL] Failed to download all specified files. Exiting. Exception: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Program.DownloadFileWithRetries(String fileUri, String downloadDir, Int32 maxRetryCount, Int32 retryIntervalInSeconds)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Program.DownloadFiles(IList`1 fileUriStrs, ProtectedSettings storageAccountSettings, String downloadDir)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Program.Main(String[] args)
...


As indicated by @jjburr above, a recent [**commit**](https://github.com/Azure/azure-quickstart-templates/commit/c4e9d4c92191ebe3354b776a87b30a060b55d132#diff-9d78c53a1876d05ca9fd04558c134fdf) appears to have deleted **winrmconf.cmd**, and this appears to be the cause of the failure.

Please advise urgently.

**Comment by sadeyemo** [comment]
winrmconf.cmd appears to have been restored; many thanks.

**Comment by blue00** [comment]
And now it is gone again. (404)
