### ISSUE TITLE
dynamic key names?

### ISSUE THREAD

**Issue by mkliu** [Azure/azure-quickstart-templates#496]
I'm creating a template for azure website. Trying to add a connection string, but I want the name of the string to be passed in as a parameter. So that the template can be more generic for various projects.

obviously the following doesn't work. Any suggestions?

```
                {
                    "apiVersion": "2015-04-01",
                    "name": "connectionstrings",
                    "type": "config",
                    "properties": {
                        "[parameters['connStringName]": {
                            "value": "[parameters('sqlConn')]",
                            "type": "SQLAzure"
                        }
                    }
                }
```

Complaining:
```
verbose: Error: Deployment template validation failed: 'The template resource 'connectionstrings' at line '1' and column '1959' is not valid: Template language expression '[parameters('connStringName')]' is not expected at this location..'.
    at Function.ServiceClient._normalizeError (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

**Comment by singhkay** [comment]
Adding @davidebbo for help

**Comment by davidebbo** [comment]
It's not supported by the template engine as far as I know. Though I agree that ideally it would work. @IlyaGrebnov might have input here.

**Comment by mkliu** [comment]
for things like appSettings, connectionStrings, where names are specified by users, this type of quests will definitely come up. Can you guys add this to feature request?

**Comment by davidebbo** [comment]
This is tracked by https://github.com/JamesNK/Newtonsoft.Json/issues/633. @singhkay, should probably close this one.

**Comment by davidebbo** [comment]
Oops, my bad, ignore my previous comment. The issue I pointed to relates to something that's needed for the implementation, but does not track the work item discussed here.

**Comment by davidebbo** [comment]
Good news: the change to support this is coming. Should be available is a couple of weeks.

**Comment by mkliu** [comment]
@davidebbo awesome. Any github issue tracking this?

**Comment by davidebbo** [comment]
Sorry, no, this particular logic is not in code that's on GitHub.
