### ISSUE TITLE
101-vms-with-selfhost-integration-runtime/gatewayInstall.ps1 diacmd.exe Failed to run process: exitCode=-2146233088

### ISSUE THREAD

**Issue by darivuki** [Azure/azure-quickstart-templates#7425]
[101-vms-with-selfhost-integration-runtime](https://github.com/Azure/azure-quickstart-templates/tree/master/101-vms-with-selfhost-integration-runtime)

### Issue Details
When deploying the arm template, the gatewayInstall.ps1 script fails to run the process to start the integration runtime with the following error as seen in 

**Azure Activity logs**:

"{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceDeploymentFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"VMExtensionProvisioningError\",\"message\":\"VM has reported a failure when processing extension 'didevwe-vm0installGW'. Error message: \\\"Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'Failed to run process: exitCode=-2146233088, errVariable=, errContent=, \\r\\noutContent=Microsoft.DataTransfer.DIAgentClient.HostServiceException: The \\r\\nnamed pipe cannot be established in expect time 60000(ms), please restart the \\r\\nhost service and have a tr...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot \"}]}}"

**And these are the logs from the log file of the script:**

Start to excute gatewayInstall.ps1. 

2020-04-21 09:26:08 Log file: C:\WindowsAzure\Logs\Plugins\Microsoft.Compute.CustomScriptExtension\

2020-04-21 09:26:08 Gateway download fw link: https://go.microsoft.com/fwlink/?linkid=839822

2020-04-21 09:26:08 Gateway download location: C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.5\Downloads\1\gateway.msi

2020-04-21 09:26:15 Download gateway successfully. Gateway loc: C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.5\Downloads\1\gateway.msi

2020-04-21 09:26:15 Start Gateway installation

2020-04-21 09:27:30 Run-Process: ExitCode=0, output=

2020-04-21 09:28:00 Installation of gateway is successful

2020-04-21 09:28:00 Register Agent

2020-04-21 09:28:00 Get-RegistryProperty: Get DiacmdPath from hklm:\Software\Microsoft\DataTransfer\DataManagementGateway\ConfigurationManager

2020-04-21 09:28:00 Gateway installation file: C:\Program Files\Microsoft Integration Runtime\4.0\Shared\diacmd.exe

2020-04-21 09:29:02 DMDTTP is failed: Failed to run process: exitCode=-2146233088, errVariable=, errContent=, outContent=Microsoft.DataTransfer.DIAgentClient.HostServiceException: The named pipe cannot be established in expect time 60000(ms), please restart the host service and have a try again.
   at Microsoft.DataTransfer.DIAgentClient.NamedPipeStreamProvider.SendRequest[T,TResult](T value)
   at Microsoft.DataTransfer.DIAgentCommandLine.NetworkOptions.EnableRemoteAccess(String portString, String thumbprint, Boolean container)
   at Microsoft.DataTransfer.DIAgentCommandLine.NetworkOptions.RunNetworkOptions(CommandLineOptions options)
   at Microsoft.DataTransfer.DIAgentCommandLine.Program.RunCommands(CommandLineOptions options)
   at Microsoft.DataTransfer.DIAgentCommandLine.Program.Main(String[] args)
.
Stack:
at Throw-Error, C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.5\Downloads\1\gatewayInstall.ps1: line 24
at Run-Process, C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.5\Downloads\1\gatewayInstall.ps1: line 79
at Register-Gateway, C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.5\Downloads\1\gatewayInstall.ps1: line 163
at <ScriptBlock>, C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.5\Downloads\1\gatewayInstall.ps1: line 180

What went wrong?

Thanks,
Davor

**Comment by darivuki** [comment]
The problem in my case was that I was releasing this through Azure DevOps multiple times and the gatewayInstall.ps1 script is trying to download, install and start the integration process again which causes this issue. As a quick workaround, I have added an if-else statement to check for the running process:

if ((Get-Process "diahost" -ea SilentlyContinue) -eq $Null)
{ 
	Trace-Log "Integration Runtime is not running. Initiating Download - Install - Register sequence." 
	
	Trace-Log "Log file: $logLoc"
	$uri = "https://go.microsoft.com/fwlink/?linkid=839822"
	Trace-Log "Gateway download fw link: $uri"
	$gwPath= "$PWD\gateway.msi"
	Trace-Log "Gateway download location: $gwPath"

	Download-Gateway $uri $gwPath
	Install-Gateway $gwPath

	Register-Gateway $gatewayKey
}
else
{ 
	Trace-Log "Integration Runtime is already running. Skipping installation & configuration."
}
